### ISSUE TITLE
初次运行网络代理报错，请问该如何处理？（clash tun mode 已经打开）

### ISSUE THREAD

**Issue by jasondong1104** [nishuzumi/gemini-teacher#16]
语音模式关闭，找不到 ELEVENLABS_API_KEY
Traceback (most recent call last):
  File "d:\projects\gemini-teacher\starter.py", line 250, in <module>
    asyncio.run(main.run())
  File "C:\Users\Jiasheng\.conda\envs\env-python3.11\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Jiasheng\.conda\envs\env-python3.11\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jiasheng\.conda\envs\env-python3.11\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
    async with proxy_connect(
  File "C:\Users\Jiasheng\.conda\envs\env-python3.11\Lib\site-packages\websockets\legacy\client.py", line 632, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\Jiasheng\.conda\envs\env-python3.11\Lib\site-packages\websockets_proxy\websockets_proxy.py", line 54, in __await_impl_proxy__
    sock = await self.__proxy.connect(
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connect'

**Comment by jasondong1104** [comment]
发现根因了，是因为.env文件里没加网络代理环境变量

**Comment by jasondong1104** [comment]
发现根因了，是因为.env文件里没加网络代理环境变量

**Comment by zhangnanchao** [comment]
同样的问题，能发个示例吗

**Comment by jasondong1104** [comment]
> 同样的问题，能发个示例吗

![image](https://github.com/user-attachments/assets/0034deaa-a17a-47dd-96de-63524e06d428)
