### ISSUE TITLE
运行过程中出现麦克风兼容问题？

### ISSUE THREAD

**Issue by longwutu** [nishuzumi/gemini-teacher#20]
============================================
初始化完成 ✅
Error: [Errno -9999] Unanticipated host error
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<AudioLoop.run() done, defined at E:\gemini-teacher-master\starter.py:227> exception=ExceptionGroup('unhandled errors in a TaskGroup', [OSError(-9999, 'Unanticipated host error')])>
  + Exception Group Traceback (most recent call last):
  |   File "E:\gemini-teacher-master\starter.py", line 256, in run
  |     async with asyncio.TaskGroup() as tg:
  |   File "C:\Users\DNB-1171\.conda\envs\gemini-teacher-master\Lib\asyncio\taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "E:\gemini-teacher-master\starter.py", line 128, in listen_audio
    |     stream = pya.open(
    |              ^^^^^^^^^
    |   File "C:\Users\DNB-1171\.conda\envs\gemini-teacher-master\Lib\site-packages\pyaudio\__init__.py", line 639, in open
    |     stream = PyAudio.Stream(self, *args, **kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\DNB-1171\.conda\envs\gemini-teacher-master\Lib\site-packages\pyaudio\__init__.py", line 441, in __init__
    |     self._stream = pa.open(**arguments)
    |                    ^^^^^^^^^^^^^^^^^^^^
    | OSError: [Errno -9999] Unanticipated host error
    +------------------------------------

我通过代码
        # mic_info = pya.get_device_info_by_index(1)  # 使用索引1的设备，即“阵列麦克风 (AMD Audio Device)”
问题依旧存在
获取麦克风阵列信息如下
import pyaudio

pa = pyaudio.PyAudio()
info = pa.get_default_input_device_info()
print(info)
运行后：
{'index': 1, 'structVersion': 2, 'name': '阵列麦克风 (AMD Audio Device)', 'hostApi': 0, 'maxInputChannels': 2, 'maxOutputChannels': 0, 'defaultLowInputLatency': 0.09, 'defaultLowOutputLatency': 0.09, 'defaultHighInputLatency': 0.18, 'defaultHighOutputLatency': 0.18, 'defaultSampleRate': 44100.0}
大佬，请问是哪方面出了问题？是麦克风驱动不兼容吗？

**Comment by nishuzumi** [comment]
这个我还真是第一次见，阵列麦克风感觉也不是一个正常的麦克风设备？
